spec_version: 2
description: Blueprint for nginx helm chart in custom cluster

inputs:
  agent:
    type: agent
  target-namespace:
    type: string
    default: "sveta-test"
  secret-name:
    type: string
    default: "playground-config"
  destination-context-name:
    type: string
    default: "playground-eks"

grains:
  nginx:
    kind: helm
    spec:
      source:
        store: test-spec2-public
        path: helm/nginx-test
      agent:
        name: '{{ .inputs.agent }}'
        service-account: remote-cluster-accessor
        kubernetes:
          permissions:
            # secret-namespace is the runner namespace which is the agent's default namespace
            secret-name: '{{ inputs.secret-name }}'
            destination-context-name: '{{ inputs.destination-context-name }}'
      target-namespace: '{{ inputs.target-namespace }}'
      commands:
        - dep up helm/nginx-test
